// Golden screenshot tests.
//
// These tests render key screens to PNG files so that reviewers can inspect
// the UI look-and-feel without running a device.  They are tagged 'golden'
// so that the normal CI test run can skip them (they are generated by a
// dedicated ui-screenshots CI job that runs with --update-goldens).
//
// To regenerate locally:
//   flutter test --update-goldens test/golden_screenshots_test.dart
//
// Generated files land in test/goldens/ (committed to the repo so they are
// visible as image diffs in PRs).

@Tags(['golden'])
library;

import 'package:flutter/material.dart';
import 'package:flutter_test/flutter_test.dart';
import 'package:kingtrux/ui/kingtrux_login_page.dart';
import 'package:kingtrux/ui/preview_gallery_page.dart';

/// Phone viewport matching a common device (iPhone 14-class / Pixel 7-class).
const Size _kPhoneSize = Size(390, 844);

void main() {
  // ── Login page ────────────────────────────────────────────────────────────

  testWidgets('golden: login page (light)', (WidgetTester tester) async {
    await tester.binding.setSurfaceSize(_kPhoneSize);
    addTearDown(() => tester.binding.setSurfaceSize(null));

    await tester.pumpWidget(
      const MaterialApp(home: KingtruxLoginPage()),
    );
    await tester.pumpAndSettle();

    await expectLater(
      find.byType(KingtruxLoginPage),
      matchesGoldenFile('goldens/login_page.png'),
    );
  });

  // ── Preview gallery (top of page, light theme) ───────────────────────────

  testWidgets('golden: preview gallery page', (WidgetTester tester) async {
    await tester.binding.setSurfaceSize(_kPhoneSize);
    addTearDown(() => tester.binding.setSurfaceSize(null));

    await tester.pumpWidget(buildPreviewGalleryApp());
    await tester.pumpAndSettle();

    await expectLater(
      find.byType(PreviewGalleryPage),
      matchesGoldenFile('goldens/preview_gallery.png'),
    );
  });
}
