// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  // API keys are injected at CI build time via --dart-define or sed replacement.
  // Replace each YOUR_*_FIREBASE_API_KEY placeholder with the real value from your
  // Firebase Console before building locally (or set up GitHub Secrets — see
  // docs/FIREBASE_SETUP.md for instructions).

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'YOUR_WEB_FIREBASE_API_KEY',
    appId: '1:802226888759:web:4a64ff7011e28876c8dfb2',
    messagingSenderId: '802226888759',
    projectId: 'kingtrux-387ae',
    authDomain: 'kingtrux-387ae.firebaseapp.com',
    storageBucket: 'kingtrux-387ae.firebasestorage.app',
    measurementId: 'G-Z6V2J4RCG4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'YOUR_ANDROID_FIREBASE_API_KEY',
    appId: '1:802226888759:android:b1b70f1fc3171a81c8dfb2',
    messagingSenderId: '802226888759',
    projectId: 'kingtrux-387ae',
    storageBucket: 'kingtrux-387ae.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'YOUR_IOS_FIREBASE_API_KEY',
    appId: '1:802226888759:ios:f986a91d615a979bc8dfb2',
    messagingSenderId: '802226888759',
    projectId: 'kingtrux-387ae',
    storageBucket: 'kingtrux-387ae.firebasestorage.app',
    iosClientId: '802226888759-fkjd6baqvt8incepij3i7qbrvosfdst7.apps.googleusercontent.com',
    iosBundleId: 'com.example.duken',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'YOUR_IOS_FIREBASE_API_KEY',
    appId: '1:802226888759:ios:f986a91d615a979bc8dfb2',
    messagingSenderId: '802226888759',
    projectId: 'kingtrux-387ae',
    storageBucket: 'kingtrux-387ae.firebasestorage.app',
    iosClientId: '802226888759-fkjd6baqvt8incepij3i7qbrvosfdst7.apps.googleusercontent.com',
    iosBundleId: 'com.example.duken',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'YOUR_WEB_FIREBASE_API_KEY',
    appId: '1:802226888759:web:efeb0213973bcc1bc8dfb2',
    messagingSenderId: '802226888759',
    projectId: 'kingtrux-387ae',
    authDomain: 'kingtrux-387ae.firebaseapp.com',
    storageBucket: 'kingtrux-387ae.firebasestorage.app',
    measurementId: 'G-JFYCT9S7NS',
  );
}
